console.log("wordlist is loaded");

var WordList = {

  options: [
   {category: "Thanksgiving",
    words: ["cornucopia",
            "cranberries",
            "drumstick",
            "leftovers",
            "football",
            "squash",
            "wishbone",
            "stuffing",
            "gobble",
            "giblets",
            "pumpkin pie",
            "acorns",
            "turkey",
            "casserole",
            "mayflower",
            "pilgrims",
            "gravy",
            "candied yams",
            "sweet potato",
            "native american",
            "apple pie",
            "cornbread",
            "centerpiece",
            "jello mold"]
          },
   {category: "Mythology",
    words: ["cornucopia",
            "cranberries",
            "drumstick",
            "leftovers",
            "football",
            "squash",
            "wishbone",
            "stuffing",
            "gobble",
            "giblets",
            "pumpkin pie",
            "acorns",
            "turkey",
            "casserole",
            "mayflower",
            "pilgrims",
            "gravy",
            "candied yams",
            "sweet potato",
            "native american",
            "apple pie",
            "cornbread",
            "centerpiece",
            "jello mold"]
          },
   {category: "Hobbies",
    words: ["cornucopia",
            "cranberries",
            "drumstick",
            "leftovers",
            "football",
            "squash",
            "wishbone",
            "stuffing",
            "gobble",
            "giblets",
            "pumpkin pie",
            "acorns",
            "turkey",
            "casserole",
            "mayflower",
            "pilgrims",
            "gravy",
            "candied yams",
            "sweet potato",
            "native american",
            "apple pie",
            "cornbread",
            "centerpiece",
            "jello mold"]
          }
  
    ]        
  
  };


module.exports = WordList;