 // console.log("wordlist is loaded");

var WordList = {

  options: [
   {category: "Thanksgiving",
    words: ["cornucopia",
            "cranberry sauce",
            "drumstick",
            "leftovers",
            "football", 
            "squash",
            "indian corn",
            "black friday",
            "wishbone",
            "stuffing",
            "gobble",
            "giblets",
            "pumpkin pie",
            "acorns",
            "tryptophan",
            "turkey",
            "green bean casserole",
            "pecan pie",
            "mayflower",
            "pilgrims",
            "giving thanks",
            "mashed potatoes",
            "presidential pardon",
            "gravy",
            "candied yams",
            "sweet potato",
            "native american",
            "busiest travel day",
            "apple pie",
            "cornbread",
            "centerpiece",
            "jello mold"]
          },
   {category: "Alliteration",
    words: ["beat around the bush",
            "belle of the ball",
            "bet your bottom dollar",
            "bottom of the barrel",
            "forgive and forget",
            "feast or famine",
            "all that glitters is not gold",
            "grass is greener",
            "dastardly deed",
            "dead as a doornail",
            "fast and furious",
            "cream of the crop",
            "cool as a cucumber",
            "leaping lizards",
            "mind over matter",
            "naughty or nice",
            "party pooper",
            "practice makes perfect",
            "rabble rouser",
            "better safe than sorry",
            "sunny side of the street",
            "thick as thieves",
            "tongue twisters",
            "trials and tribulations",
            "walking wounded",
            "whistle while you work",
            "yin and yang",
            "add insult to injury",
            "fall head over heels",
            "vim and vigor",
            "fancy footwork",
            "common courtesy",
            "pitter patter",
            "treasure trove"]
          },
   {category: "Computers",
    words: ["algorithm",
            "analog",
            "bandwidth",
            "browser",
            "cloud computing",
            "cookie",
            "database",
            "development",
            "encryption",
            "hyperlink",
            "iteration",
            "open source",
            "phishing",
            "protocol",
            "queue",
            "resolution",
            "social networking",
            "text editor",
            "user interface",
            "webmaster",
            "search engine",
            "cache",
            "flowchart",
            "dot matrix"]
          }
  
    ]        
  
  };


module.exports = WordList;